# Theme
theme: minimal-mistakes-jekyll

# Site Settings
locale                   : "en"
title                    : "Scholar"
title_separator          : "-"
name                     : "Konstantinos Chorianopoulos"
description              : "Research articles and more."
url                      : "http://scholar.epidro.me"
baseurl                  :
repository               :
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
search                   : false

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  news:
    output: false
  pages:
    output: true
    permalink: pretty

news_limit: 6

defaults:
  - scope:
      path: "_news"
      type: news
    values:
      layout: posts
      inline: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

author:
  name             : "Konstantinos Chorianopoulos"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Ionian University"
  location         : "Corfu, Greece"
  keybase          : #'epidrome'
  e-mail           : "choko@ionio.gr"
  homepage         : #"https://users.ionio.gr/choko"
  cv               : "en/resume.pdf"
  github-alt       : #"epidrome"
  google-scholar   : #"EnRHC-4AAAAJ"
  orcid            : "0000-0002-5999-9387"

scholar:
  style: acm-siggraph
  locale: en

  sort_by: year
  order: descending

  source: ./_bib
  bibliography: papers.bib
  bibliography_template: entry

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
    - latex

  repository: 'http://pdf.epidro.me'

  query: "@*"
